Cover afterException hook with tests
LibreSign/libresign pull request #2004
Opened 2023-12-16 20:02 UTC by vitormattos

2023-12-16 21:58 UTC, giovannism20 commented
I understand that in fact whatever the request is, it should be interpreted as a client and there should not be this difference "The client could be a request from API or a request made from user". And therefore, I think we should standardize JSON in the response and the device interested in the request response would worry about parsing the data. But we can discuss more about it.

2023-12-16 21:59 UTC, giovannism20 approved these changes

2023-12-16 22:00 UTC, giovannism20 requested changes
Wrong approval, sorry.

2023-12-17 19:16 UTC, vitormattos commented
Sure @giovannism20 
I maintained this PR as draft because I can't go ahead without made a best clarify round about this pattern and finish this implementation (is incomplete).

This is a very important point of app and will be very nice to make a brainstorm call about with other engineers and create a good pattern and  define how backend will send the data to front after an access to sign url.

2023-12-18 19:35 UTC, giovannism20 approved these changes

2023-12-18 19:35 UTC, merged

2023-12-21 14:22 UTC, vitormattos commented
/backport to stable28