Validation date format
LibreSign/libresign pull request #234
Opened 2021-05-14 03:26 UTC by raw-vitor

correct validation data format

2021-05-14 03:32 UTC, vitormattos requested changes

2021-05-14 03:32 UTC, vitormattos commented on src/views/Validation.vue
> +			assignedMessage: t('libresign', 'signed at'),
Use placeholders
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html?highlight=translate#javascript

2021-05-14 13:01 UTC, vinicios-gomes approved these changes

2021-05-14 13:10 UTC, vinicios-gomes approved these changes

2021-05-19 00:38 UTC, vinicios-gomes approved these changes

2021-05-19 00:38 UTC, merged