Update helper text on the modal to indicate usage on multi-page documents
LibreSign/libresign pull request #2915
Opened 2024-04-26 19:19 UTC by metheos

### Pull Request Description
Updates the text on the signature placement modal to better explain how to place a signature on any page.

### Related Issue
Issue Number: 2903

### Pull Request Type
Other: Text Change

2024-04-27 13:46 UTC, vitormattos requested changes
Thanks a lot by your contribution!

Could you fix the DCO issue?

Follow the instructions:

https://github.com/LibreSign/libresign/pull/2915/checks?check_run_id=24313652582

2024-04-27 13:46 UTC, vitormattos commented on src/Components/Request/VisibleElements.vue
> +					{{ t('libresign', 'Click the page to sign, then select a signer to set their signature position') }}
What you think about this suggestion?

```suggestion
					{{ t('libresign', 'Click the page to add visible signature, then select a signer to set their signature position') }}
```

Is possible to sign without visible signature. If you don't want to add visible signature, you only need to ignore this step and go ahead.

2024-04-29 13:35 UTC, metheos reviewed
Looks good. I think I fixed the PR, DCO shows green 👍
I enabled 'always add sign-off' in my vscode editor's git

2024-04-29 13:38 UTC, vitormattos commented
Workded fine now!
Thanks!
The problem now is about the commit message. We followed at LibreSign the same pattern to commit messages of Nextcloud server and other apps of Nextcloud organization.
https://www.conventionalcommits.org/
I will accept your PR and we need to think more about how to help contributors to don't have problems with this pattern. This is not a block at your PR.

2024-04-29 13:39 UTC, vitormattos commented
/backport to stable28

2024-04-29 13:39 UTC, merged

2024-04-29 13:45 UTC, metheos commented
Thanks. I would like to contribute more in the future to this and other nextcloud projects, so I'll try to follow those guidelines next time ⭐