Page to sign account file
LibreSign/libresign pull request #615
Opened 2022-02-08 00:41 UTC by vitormattos

2022-02-08 02:54 UTC, vinicius73 requested changes

2022-02-08 02:54 UTC, vinicius73 commented on appinfo/routes.php
> +		['name' => 'page#signAccountFile',            'url' => '/p/accout/files/approve/{uuid}/{path}', 'verb' => 'GET', 'requirements' => ['path' => '.+'], 'postfix' => 'extra'],
**typo:** account

2022-02-08 03:20 UTC, vitormattos commented on appinfo/routes.php
> +		['name' => 'page#signAccountFile',            'url' => '/p/accout/files/approve/{uuid}/{path}', 'verb' => 'GET', 'requirements' => ['path' => '.+'], 'postfix' => 'extra'],
```suggestion
		['name' => 'page#signAccountFile',            'url' => '/p/account/files/approve/{uuid}', 'verb' => 'GET'],
		['name' => 'page#signAccountFile',            'url' => '/p/account/files/approve/{uuid}/{path}', 'verb' => 'GET', 'requirements' => ['path' => '.+'], 'postfix' => 'extra'],
```

2022-02-09 19:15 UTC, merged

2022-02-09 19:15 UTC, vitormattos commented
/backport to stable23

2022-02-09 19:16 UTC, vitormattos commented
/backport to stable22

2022-02-09 19:16 UTC, vitormattos commented
/backport to stable21